name:                rmExif
version:             0.1.0.0
github:              "naoto-ogawa/rmExif"
license:             MIT
author:              "Naoto Ogawa"
maintainer:          "becausethespiderspiedher@gmail.com"
copyright:           "2019 Naoto Ogawa"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/rmExif#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - binary
  - bytestring
  - directory

executables:
  rmExif-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rmExif

tests:
  rmExif-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rmExif
